# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CreateComponentDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CreateComponentDemo
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.0'

  pod 'Masonry'
  pod 'AFNetworking'
  pod 'JLRoutes'


end
